version: "3.8"
volumes:
    php-fpm-socket:
    db-store:
    vendor-store:
    node_modules-store:

services:
    app:
        build:
            context: .
            dockerfile: ./infra/docker/php/Dockerfile
        volumes:
            - php-fpm-socket:/var/run/php-fpm
            - .:/src
            - vendor-store:/src/vendor
            - node_modules-store:/src/node_modules

    web:
        build:
            context: .
            dockerfile: ./infra/docker/nginx/Dockerfile
        ports:
            - ${WEB_PORT:-80}:80
        volumes:
            - php-fpm-socket:/var/run/php-fpm
            - .:/src
            - node_modules-store:/src/node_modules

    db:
        build:
            context: .
            dockerfile: ./infra/docker/mysql/Dockerfile
        ports:
            - ${DB_PORT:-3306}:3306
        volumes:
            - db-store:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-edule_pw}

    adminer:
        image: adminer
        ports:
            - 8080:8080
        links:
            - db
